### ISSUE TITLE
slider UI elements appearance

### ISSUE THREAD

**Issue by tischi** [mcib3d/mcib3d-plugins#15] opened 2018-03-26 11:08 UTC
After running the 3D Image Suite the appearance of the sliders below the images is different.
We feel that this does not really increase usability and for UI elements like the threshold adjustment it really makes it very difficult to use them:

![image](https://user-images.githubusercontent.com/2157566/37903027-b127a494-30f6-11e8-8b58-f422166bd850.png)

Is there are reason that you want to change the UI slider element appearance?

**Comment by imagejan** [comment] 2018-03-26 11:15
This might be caused by `RoiManager3D_2.java` changing the `javax.swing` Look-And-Feel here:

https://github.com/mcib3d/mcib3d-plugins/blob/c67e72e4b671a98e5a5daad48d54dd520e101b47/src/main/java/mcib_plugins/tools/RoiManager3D_2.java#L171-L197

I suggest not doing this, as it can mess up other components of ImageJ that are not properly using the Swing UI or making false assumptions about the width and height of UI elements in the standard look-and-feel.

**Comment by mcib3d** [comment] 2018-03-27 04:18
Hi,

On my system (Linux) only the open file dialog is modified, not the thresholding window. Maybe best is to have this LooknFeel optional.

**Comment by tischi** [comment] 2018-03-27 05:36
On my Mac it changes all UI elements that are opened afterwards.  Making it optional (with default: "don't change", at least on Mac) sounds like a good idea, because also visitors that I am helping right now with image analysis told me that after using RoiManager_3D they basically always need to restart their Fiji :)

**Comment by mcib3d** [comment] 2018-04-13 04:47
Fixed in 090254bc0b8c925e2972b998d645dd6933a98cc7

**Closed as completed by mcib3d** 2018-04-13 04:47 UTC

**Comment by tischi** [comment] 2018-04-26 08:22
@mcib3d 
Thank you for fixing it!
I think there is still one issue left: When clicking on [ 3D Segmentation ] in the 3D Roi Manager it still changes the UI mode:
![image](https://user-images.githubusercontent.com/2157566/39294321-be51c426-493b-11e8-8d0b-5439a274fe4b.png)
